# Generated by Django 5.0.6 on 2024-06-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('hours', models.CharField(max_length=100)),
                ('return_policy', models.TextField()),
                ('shipping_info', models.TextField()),
                ('special_offers', models.TextField()),
            ],
        ),
    ]
